name: Auto Approve
# このGitHub Actionsを起動するイベントの種類
on:
  # Pull Request関係のイベント
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review # Draft pull RequestからDraftが外れたら起動
jobs:
  approve:
  # このJobを実行する条件。以下すべてを満たす場合実行。
  # + Pull Requestの作成者が、リポジトリの所有者と等しい
  # + Pull Requestが、Draft Pull Requestではない
    if:
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    # このJobを実行するときに使用するOS
    # 今回は何でもいいが、GitHub Actionsでは指定が必要
    runs-on: ubuntu-latest
    # 内部で使用されているGitHub APIを上書き
    permissions:
      pull_requests: write
    steps:
      # Pull RequestをApproveする
      - uses: hmarr/auto-approve-action@v3
